In [2]:
import numpy as np
def printl():
    print("==========================")

In [2]:
array = np.array([[1,2,3],
                  [3,4,5]])

# array的基本属性

In [4]:
print(array.ndim)
print(array.shape)
print(array.size)

2
(2, 3)
6


# dtype 

In [15]:

array_tpye = np.array([[1,2,3],[4,5,6]],dtype = np.int) # 这里要是 np的int
print(array_tpye.dtype)
print(array_tpye)
array_tpye2 = np.array([[1,2,3],[4,5,6]],dtype = np.float32) # 这里要是 np的float 才可以跟位数
print(array_tpye2.dtype)
print(array_tpye2)

int64
[[1 2 3]
 [4 5 6]]
float32
[[1. 2. 3.]
 [4. 5. 6.]]


# 创建矩阵

In [55]:
a = np.zeros((2,3))
print(a)
b = np.ones((2,3))
print(b)
c = np.empty((2,3))
print(c)
d = np.linspace(1,10,6)
print(d)
e = np.arange(12)
print(e)
f = np.random.random((3,4))
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 1.   2.8  4.6  6.4  8.2 10. ]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[0.17120838 0.53396391 0.38762104 0.35533082]
 [0.94837849 0.08937309 0.94228578 0.64544695]
 [0.12983056 0.59738947 0.34189979 0.03719368]]


# reshape
reshapes是浅拷贝，内部数据会跟着原来的变化而变化，但两个array的内存地址是不一样的

In [30]:
a = np.arange(12)
print(a)
b = a.reshape((4,3))
a[0]= 100
print(a)
print(b)
print(id(a))
print(id(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]
4645157264
4645157904


# 运算

In [57]:
a = np.array([[1,2,3],[2,3,4]])
b = np.arange(3)
print(a,  "\n" ,b)
print(np.sin(a))
print(a**2)
print(np.exp(a))
print(a+b)
print(a<3)

[[1 2 3]
 [2 3 4]] 
 [0 1 2]
[[ 0.84147098  0.90929743  0.14112001]
 [ 0.90929743  0.14112001 -0.7568025 ]]
[[ 1  4  9]
 [ 4  9 16]]
[[ 2.71828183  7.3890561  20.08553692]
 [ 7.3890561  20.08553692 54.59815003]]
[[1 3 5]
 [2 4 6]]
[[ True  True False]
 [ True False False]]


In [58]:
print(a*b) # 逐个相乘
print(np.dot(a,b)) # 矩阵点积
print(a@b)
print(a.dot(b))

[[0 2 6]
 [0 3 8]]
[ 8 11]
[ 8 11]
[ 8 11]


In [64]:
a = np.array([[1,2,3],[2,3,4]])
b = np.arange(3)
print(a)
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.max(a,axis = 1)) # 1是行  0是列
print(np.max(a,axis = 0))

[[1 2 3]
 [2 3 4]]
4
1
15
[3 4]
[2 3 4]


In [76]:
a = np.arange(2,14).reshape((3,4))
print(a)
print(np.argmin(a))
print(np.argmax(a,axis=0))
print(a.mean())
print(a.mean(axis = 0))
print(np.mean(a,axis = 0))

# 中位数
print(np.median(a,axis = 1))
print(np.cumsum(a))
print(np.diff(a))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
[2 2 2 2]
7.5
[6. 7. 8. 9.]
[6. 7. 8. 9.]
[ 3.5  7.5 11.5]
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [89]:
a = np.array([[2,0,3],[1,0,0]])
print(a)
print(np.nonzero(a))
# 坐标00 01 02为非0
print(np.sort(a)) # 只对一行进行排序
print(np.transpose(a))
print(a.T)
print(np.clip(a,1,2)) # 设定最小最大，把超出范围的都拉到范围

[[2 0 3]
 [1 0 0]]
(array([0, 0, 1]), array([0, 2, 0]))
[[0 2 3]
 [0 0 1]]
[[2 1]
 [0 0]
 [3 0]]
[[2 1]
 [0 0]
 [3 0]]
[[2 1 2]
 [1 1 1]]


# 切片和索引


In [93]:
a = np.array([[2,3,4],[11,45,9],[1,4,5]])
print(a)
print(a[1][2])
print(a[1][:])

[[ 2  3  4]
 [11 45  9]
 [ 1  4  5]]
9
[11 45  9]


In [133]:
# for循环默认迭代行，如果想迭代列，T一下
for row in a:
    print(row)
printl()
for col in a.T:
    print(col)
printl()
print(a.flatten())
for item in a.flat:
    print(item)
printl()
for item in a.flatten():
    print(item)

1
2
3
1
2
3
[1 2 3]
1
2
3
1
2
3


# 叠加 分割

In [132]:
a = np.array([1,2,3])
b = np.array([0,0,1])
print(np.vstack((a,b)))

print(np.hstack((a,b)))
print(a.shape)
printl()
print(a[np.newaxis,:])
print(a[np.newaxis,:].shape)
printl()
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)
printl()
print(a.reshape(1,3))

[[1 2 3]
 [0 0 1]]
[1 2 3 0 0 1]
(3,)
[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]


In [128]:
a = np.array([1,2,3]).reshape(3,1)
b = np.array([0,0,1]).reshape(3,1)
print(a.shape)
# axis 表示第几个纬度，就是shape中的第几个数，按照那个纬度叠加
print(np.concatenate((a,b,a),axis = 0))
print(np.concatenate((a,b,a),axis = 1))

(3, 1)
[[1]
 [2]
 [3]
 [0]
 [0]
 [1]
 [1]
 [2]
 [3]]
[[1 0 1]
 [2 0 2]
 [3 1 3]]


In [136]:
a = np.arange(12).reshape((3,4))
print(a)
print(np.split(a,2,axis = 1))
printl()
# 不对称也能分割
print(np.array_split(a,3,axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


# copy 问题
copy是deepcopy

In [143]:
a = np.array([[1,2,3]])
b = a.copy() # deepcopy
a[0][1] = 30
print(a)
print(b)

[[ 1 30  3]]
[[1 2 3]]


切片是浅拷贝

In [144]:
a = np.array([[1,2,3],[3,4,5]])
b = a[1][:]
a[1][2] = 30
print(a)
print(b)
print(id(a),id(b))

[[ 1  2  3]
 [ 3  4 30]]
[ 3  4 30]
4645473216 4645325760


# 提速
不管是1D/2D/3D 的 Array, 从根本上, 它都是一个 1D array!

In [3]:
col_major = np.zeros((10,10), order='C')    # C-type
row_major = np.zeros((10,10), order='F')    # Fortran

In [9]:
import time
a = np.zeros((200, 200), order='C')
b = np.zeros((200, 200), order='F')
N = 9999

def f1(a):
    for _ in range(N):
        np.concatenate((a, a), axis=0)

def f2(b):
    for _ in range(N):
        np.concatenate((b, b), axis=0)

t0 = time.time()
f1(a)
t1 = time.time()
f2(b)
t2 = time.time()

print((t1-t0)/N)     # 0.000040
print((t2-t1)/N)     # 0.000070

2.9450953632655747e-05
3.0313757541525636e-05


copy慢 view快

In [10]:
a_view1 = a[1:2, 3:6]    # 切片 slice
a_view2 = a[:100]        # 同上
a_view3 = a[::2]         # 跳步
a_view4 = a.ravel()      # 


In [ ]:
a_copy1 = a[[1,4,6], [2,4,6]]   # 用 index 选
a_copy2 = a[[True, True], [False, True]]  # 用 mask
a_copy3 = a[[1,2], :]        # 虽然 1,2 的确连在一起了, 但是他们确实是 copy
a_copy4 = a[a[1,:] != 0, :]  # fancy indexing
a_copy5 = a[np.isnan(a), :]  # fancy indexing

1.使用 np.take(), 替代用 index 选数据的方法.

上面提到了如果用index 来选数据, 像 a_copy1 = a[[1,4,6], [2,4,6]], 用 take 在大部分情况中会比这样的 a_copy1 要快.

In [13]:
a = np.random.rand(1000000, 10)
N = 99
indices = np.random.randint(0, 1000000, size=10000)

def f1(a):
    for _ in range(N):
        _ = np.take(a, indices, axis=0)

def f2(b):
    for _ in range(N):
        _ = b[indices]

print('%f' % ((t1-t0)/N))    # 0.000393
print('%f' % ((t2-t1)/N))    # 0.000569

0.002975
0.003062


2.使用 np.compress(), 替代用 mask 选数据的方法.

上面的 a_copy2 = a[[True, True], [False, True]] 这种就是用 TRUE, FALSE 来选择数据的. 测试如下:

In [14]:
mask = a[:, 0] < 0.5
def f1(a):
    for _ in range(N):
        _ = np.compress(mask, a, axis=0)

def f2(b):
    for _ in range(N):
        _ = b[mask]

print('%f' % ((t1-t0)/N))    # 0.028109
print('%f' % ((t2-t1)/N))    # 0.031013

0.002975
0.003062


out 参数
a=a+1 要先转换成 np.add() 这种形式再运算

In [16]:
a = a + 1         # 0.035230
a = np.add(a, 1)  # 0.032738

但是在功能里面有一个 out 参数, 让我们不必要重新创建一个 a. 所以下面两个是一样的功能, 都不会创建另一个 copy. 不过可能是上面提到的那个原因, 这里的运算时间也有差.

In [ ]:
a += 1                 # 0.011219
np.add(a, 1, out=a)    # 0.008843