In [1]:
import numpy as np
import numpy.matlib 
def printline():
    print("-------------------------------------")

# 对位各种运算符算，有一维一样就能广播
# 很多统计方法，没指定维数就是展开全部，指定了就按指定的算

# 1.数据类型

### `np.dtype()`
[自定义dtype](https://numpy.org/devdocs/reference/generated/numpy.dtype.html?highlight=dtype#numpy.dtype)

In [5]:
student = np.dtype([('name','S10'),('age','i1')])

d_student = np.array([('Mary',20),('Tom',22)])
print(d_student)
print(d_student.shape)

[['Mary' '20']
 ['Tom' '22']]
(2, 2)


In [6]:
d_student = np.array([('Mary',20),('Tom',22)],dtype = student)
print(d_student)
print(d_student.shape)

[(b'Mary', 20) (b'Tom', 22)]
(2,)


# 2.数组属性


### `a.ndim`

In [15]:
print(d_student.ndim)

1


### `a.shape`

In [16]:
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


每列对不上的话，不显示另外的一个

In [17]:
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)
a = np.array([[1,2,3,6,9],[4,5,6]])  
print (a.shape)


(2, 3)
(2,)


### `a.itemsize`

In [37]:
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


# 3.创建数组

### `numpy.empty(shape, dtype = float, order = 'C')` 创建随机组

In [22]:
y = np.empty([3,2], dtype = int) 
# 数组元素为随机值，因为它们未初始化。
y

array([[0, 0],
       [0, 0],
       [0, 0]])

### `numpy.zeros(shape, dtype = float, order = 'C')` 创建全0数组

In [23]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [24]:
x = np.zeros((2,2),dtype = int)
print(x)

[[0 0]
 [0 0]]


In [25]:
x = np.zeros((3,3),dtype = [('x',int),('y',int)])
print(x)

[[(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]]


### `numpy.ones(shape, dtype = None, order = 'C')` 创建全1数组

### `numpy.arange(start, stop, step, dtype)` 创建序列reshape为数组

start	起始值，默认为0  
stop	终止值（不包含）  
step	步长，默认为1  
dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。  

In [34]:
a = np.arange(5,20,2,int)
print(a)

[ 5  7  9 11 13 15 17 19]


In [35]:
print(a.reshape(2,4))

[[ 5  7  9 11]
 [13 15 17 19]]


### `np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)` 等分直线为数组

Parameters | intro
----------|-----------
start	|序列的起始值
stop	|序列的终止值（默认包含），如果endpoint为true，该值包含于数列中
num	|要生成的等步长的样本数量，默认为50
endpoint	|该值为 ture 时，数列中中包含stop值，反之不包含，默认是True
retstep|	如果为 True 时，生成的数组中会显示间距，反之不显示
dtype	|ndarray 的数据类型

In [37]:
a =np.linspace(1,10,10,retstep= True)
print(a)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


### `np.random.randn([low,high],size)` 标准正态分布数组

In [42]:
a=np.random.randn(2,3)
print(a)
printline()
a=np.random.randint(100,200,(3,3))
print(a)

[[-0.76782056 -0.15854065  0.24878549]
 [ 0.11263372  0.02942194  0.18430538]]
-------------------------------------
[[106 152 104]
 [151 147 170]
 [146 132 150]]


### `numpy.asarray(a, dtype = None, order = None)` List变为数组

In [27]:
x = [1,2,3,4]
a= np.asarray(x)
print(a)

[1 2 3 4]


In [29]:
x = [[1,2,4],[4,5,6]]
a = np.asarray(x,dtype=float)
print(a)

[[1. 2. 4.]
 [4. 5. 6.]]


### `numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)` buffer变为数组

注意：buffer 是字符串的时候，Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b

buffer	可以是任意对象，会以流的形式读入。  
dtype	返回数组的数据类型，可选  
count	读取的数据数量，默认为-1，读取所有数据。  
offset	读取的起始位置，默认为0。  

In [67]:
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


### `numpy.fromiter(iterable, dtype, count=-1)` 迭代器变为数组

In [30]:
list=range(4)
it=iter(list)
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3.]


In [31]:
a = x.reshape(2,2)
print(a)

[[0. 1.]
 [2. 3.]]


### `np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)` 等分指数线为数组

parameters| intro
-----------|--------------
start	|序列的起始值为：base ** start
stop	|序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
num	|要生成的等步长的样本数量，默认为50
endpoint	|该值为 ture 时，数列中中包含stop值，反之不包含，默认是True 
base	|对数 log 的底数
dtype	|ndarray 的数据类型

In [39]:
a = np.logspace(1,8,num = 10, base = 2, dtype = float)
print(a)

[  2.           3.42897593   5.87893797  10.0793684   17.28095582
  29.62799079  50.79683366  87.09056001 149.31571707 256.        ]


# 4.切片和索引

## 切片

###  `:` 使用

In [52]:
a = np.arange(10)
print(a)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]


冒号 : 的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。

In [53]:
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
b = a[5] 
print(b)
print(a[2:])

5
[2 3 4 5 6 7 8 9]


In [54]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
printline()
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
-------------------------------------
[[3 4 5]
 [4 5 6]]


### `...`使用

切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。
省略号表示：全部

In [55]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print(a)
printline()
print (a[...,1])   # 第2列元素，相当于：全部行的第2列
printline()
print (a[1,...])   # 第2行元素，相当于：第2行的全部列
printline()
print (a[...,1:])  # 第2列及剩下的所有元素

[[1 2 3]
 [3 4 5]
 [4 5 6]]
-------------------------------------
[2 4 5]
-------------------------------------
[3 4 5]
-------------------------------------
[[2 3]
 [4 5]
 [5 6]]


### `,` 使用 分割aixs

In [56]:
a = np.arange(9)
b = a.reshape(3,3)
print(b)
printline()
print(b[1:,2:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------------------
[[5]
 [8]]


## 索引

### 整数数组索引

In [63]:
# 数组中(0,0)，(1,1)和(2,0)位置处的元素
# ([0,1,2]) 代表 行数  [0,1,0] 代表列数
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
print(x)
printline()
# 切片中 [a,b] a,b分别代表行，列 可以是 省略号，切片，指定的整数数组
y = x[[0,1,2],  [0,1,0]]  
print (y)

[[1 2]
 [3 4]
 [5 6]]
-------------------------------------
[1 4 5]


### 布尔索引

In [64]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print (x)
printline()
# 现在我们会打印出大于 5 的元素  
print (x[x >  5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-------------------------------------
[ 6  7  8  9 10 11]


### 花式索引

`a[[],[]]` 其实和整数数组索引一样，最外层List表示索引开始，第一个元素为数组的 0维动作，第二个元素为 1 维动作，以此类推，每个纬度上，各自的内容可以为一个整数，也可以为一个数组。 逗号`,`分割axis

In [68]:
x=np.arange(32).reshape((4,2,4))
print(x)
printline()
# 这里的4，2，1，7就是行的标号
print (x[[3,2,1]])
printline()
print (x[[3,2,1],[1]])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
-------------------------------------
[[[24 25 26 27]
  [28 29 30 31]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
-------------------------------------
[[28 29 30 31]
 [20 21 22 23]
 [12 13 14 15]]


# 5.广播(Broadcast)

**数组shape向右对齐，从右往左，除了位置上是1的都要相等**

In [79]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)
print(a.shape)
print(b.shape)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
(4, 3)
(3,)


In [80]:
a = np.empty([3,4,5,3])
b = np.empty([4,1,1])
a*b

array([[[[            nan, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000, 0.00000000e+000,             nan],
         [            nan, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000,             nan, 0.00000000e+000]],

        [[            nan, 0.00000000e+000, 1.61410533e+132],
         [3.55727265e-322, 5.43472210e-323, 2.27159536e-314],
         [6.94360047e-310, 2.47032823e-323, 4.94065646e-323],
         [            nan, 0.00000000e+000, 9.89803212e+164],
         [7.11454530e-322, 5.43472210e-323, 2.27159536e-314]],

        [[1.38872009e-309, 5.90301698e-075, 2.56914136e-322],
         [            nan, 0.00000000e+000, 5.90328085e-075],
         [2.13436359e-321, 1.08694442e-322, 4.54319072e-314],
         [1.38872009e-309,             nan, 2.56914136e-322],
         [            nan, 0.00000000e+000, 2.70603272e-023]],

        [[4.26872718e-321, 1.63041663e-322, 6.81478607e-314],
  

# 6.`np.nditer(a)`迭代数组

## `order` 迭代方向

In [92]:
a = np.arange(8).reshape(2,4)
print(a)
printline()
for x in np.nditer(a):
    print(x,end=" ")
    

[[0 1 2 3]
 [4 5 6 7]]
-------------------------------------
0 1 2 3 4 5 6 7 

遍历默认是**内存布局顺序**，所以即使T一下也一样

In [93]:
print(a.T)
for x in np.nditer(a.T):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
0 1 2 3 4 5 6 7 

复制一下，新存一个就不一样了,内存状态为 04152637，复制的时候默认是按行访问 即order=‘C’

In [94]:
b = a.T.copy(order = 'C')
print(b)
printline()
for x in np.nditer(b):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
-------------------------------------
0 4 1 5 2 6 3 7 

In [95]:
b = a.T.copy()
print(b)
printline()
for x in np.nditer(b):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
-------------------------------------
0 4 1 5 2 6 3 7 

In [96]:
b = a.T.copy(order = 'F')
print(b)
printline()
for x in np.nditer(b):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
-------------------------------------
0 1 2 3 4 5 6 7 

可以通过显式设置，来强制 nditer 对象使用某种顺序：

In [97]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('以 C 风格顺序排序：')
for x in np.nditer(a, order =  'C'):  
    print (x, end=", " )
print ('\n')
print ('以 F 风格顺序排序：')
for x in np.nditer(a, order =  'F'):  
    print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


以 C 风格顺序排序：
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

以 F 风格顺序排序：
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

## `op_flags` 修改
nditer 对象有另一个可选参数 op_flags。 默认情况下，nditer 将视待迭代遍历的数组为只读对象（read-only），为了在遍历数组的同时，实现对数组元素值得修改，必须指定 read-write 或者 write-only 的模式。

In [98]:
a = np.arange(20).reshape(4,5)
print(a)
printline()
for x in np.nditer(a,op_flags = ['readwrite']):
    x[...]=x*2
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


## `flags`    输出
c_index	可以跟踪 C 顺序的索引  
f_index	可以跟踪 F 顺序的索引  
multi-index	每次迭代可以跟踪一种索引类型  
external_loop	给出的值是具有多个值的一维数组，而不是零维数组  

In [99]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('修改后的数组是：')
for x in np.nditer(a, flags =  ['external_loop'], order =  'F'):  
   print (x, end=", " )
print ('修改后的数组是：')
for x in np.nditer(a, flags =  ['c_index']):  
   print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[ 0 20 40], [ 5 25 45], [10 30 50], [15 35 55], 修改后的数组是：
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

## 广播迭代
把a，b广播成一样形状，然后一起迭代。类似zip

In [100]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

# 7.数组操作

## 修改数组形状
函数|效果
---------|-----------
reshape()|不改变数据的条件下修改形状
flat	|数组元素迭代器，类似view
flatten()	|返回一份展平数组拷贝，对拷贝所做的修改不会影响原始数组
ravel()	|返回一份展平数组拷贝

### `numpy.reshape(arr, newshape, order='C')`

### `a.flat ` 展平为迭代器，是个view

In [102]:
a = np.arange(9).reshape(3,3) 
print(a)
for element in a.flat:
    print (element)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
1
2
3
4
5
6
7
8


### `a.flatten()` 展平为 数组拷贝，深拷贝
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序

In [111]:
a = np.arange(20).reshape(4,5)
print(a)
printline()
print(a.flatten(order ="C"))
printline()
print(a.flatten(order ="F"))
printline()
print(a.flatten(order ="A"))
b = a.flatten(order ="F")
printline()
print(id(a[0,0]))
print(id(b[0]))
print(a[0,0])
print(b[0])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
-------------------------------------
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]
-------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
-------------------------------------
4602340080
4602341584
0
0


### `a.ravel(order='C')`  展平为 数组拷贝，深拷贝
### `numpy.ravel(a, order='C')`

In [119]:
a = np.arange(20).reshape(4,5)
print(a)
printline()
print(a.ravel(order = "C"))
b = a.ravel(order = "C")
b[0] = 5
print(b)
print(id(b))
print(id(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4598661488
4598661968


In [195]:
np.ravel(a,order = 'F')


array([ 0,  5, 10, 15,  1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,
        9, 14, 19])

## 翻转数组
  函数  |效果
-----------|-----------
transpose()	|对换数组的维度 
ndarray.T	|和 self.transpose() 相同
rollaxis()	|向后滚动指定的轴
swapaxes()	|对换数组的两个轴  

### `a.transpose()` `a.T`

In [120]:
a = np.arange(12).reshape(3,4)
print(a)
printline()
print(a.T)
printline()
print(a.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
-------------------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### `numpy.rollaxis(arr, axis, start) `
numpy.rollaxis 函数向后滚动特定的轴到一个特定位置
参数说明： 
arr：数组
axis：要向后滚动的轴，其它轴的相对位置不会改变  
start：要换到的轴的位置，后面的轴顺位后移。默认为零，表示换到轴0。 

In [126]:
a = np.arange(24).reshape(2,3,4)
print (a)
print(a.shape)
printline()
b = np.rollaxis(a,2)
print (b)
print(b.shape)
printline()
c = np.rollaxis(a,2,0)
print (c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
-------------------------------------
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
(4, 2, 3)
-------------------------------------
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
(4, 2, 3)


### `numpy.swapaxes(arr, axis1, axis2) `
arr：输入的数组  
axis1：对应第一个轴的整数  
axis2：对应第二个轴的整数  

In [129]:
a = np.arange(24).reshape(2,3,4) 
print (a.shape)
printline()
print (np.swapaxes(a, 2, 0).shape)

(2, 3, 4)
-------------------------------------
(4, 3, 2)


## 修改数组维度

  函数  |效果
-----------|----------
broadcast()	|产生模仿广播的对象
broadcast_to()|	将数组广播到新形状
expand_dims()	|扩展数组的形状
newaxis | 扩展数组形状
squeeze()	|从数组的形状中删除一维条目

### `np.broadcast(a,b) ` 返回numpy.broadcast，可迭代，同时拥有x，y 类似zip

In [136]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6]) 
b = np.broadcast(x,y) 
print(b)
print (b.shape)
r,c = b.iters
print (next(r), next(c))
print (next(r), next(c))
printline()

b = np.broadcast(x,y) 
c = np.zeros(b.shape)
print(c)
printline()
print (c.shape)
c.flat = [u + v for (u,v) in b]
print (c)

(3, 3)
1 4
1 5
-------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------------------
(3, 3)
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


### `numpy.broadcast_to(array, shape, subok)` 广播成某个形状
它在原始数组上返回只读视图。它通常不连续。

In [138]:
a = np.arange(4).reshape(1,4)
print (a)
printline()
print (np.broadcast_to(a,(4,4)))

[[0 1 2 3]]
-------------------------------------
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


### `numpy.expand_dims(arr, axis) `往向0的方向插入轴
函数通过在指定位置插入新的轴来扩展数组形状，
arr：输入数组  
axis：新轴插入的位置  

In [142]:
x = np.array(([1,2],[3,4]))
print(x.shape)
y = np.expand_dims(x, axis = 0)
print(y.shape)

(2, 2)
(1, 2, 2)


In [143]:
x = np.ones((3,4,5))
print(x.shape)
y = np.expand_dims(x, axis = -2)
print(y.shape)

(3, 4, 5)
(3, 4, 1, 5)


### `np.newaxis`

In [31]:
a = np.ones((3,4))
b = a[:,np.newaxis]
print(b.shape)
c = a[:,:,np.newaxis]
print(c.shape)

(3, 1, 4)
(3, 4, 1)


### `numpy.squeeze(arr, axis)`
axis不给的话，把1的全部删了，要给也只能给是1的，因为只能删1的

In [150]:
x = np.arange(9).reshape(1,3,3,1)
y = np.squeeze(x,0)
# y = np.squeeze(x,2) 会报错
print (x.shape, y.shape)

(1, 3, 3, 1) (3, 3, 1)


## 连接数组
函数|效果
----------|------------
concatenate()	|连接沿现有轴的数组序列
stack()	|沿着新的轴加入一系列数组
hstack()	|水平堆叠序列中的数组（列方向）
vstack()	|竖直堆叠序列中的数组（行方向）

### `numpy.concatenate((a1, a2, ...), axis)` 
a1, a2, ...：相同类型的数组  
axis：沿着它连接数组的轴，默认为 0

In [151]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print (np.concatenate((a,b)))
printline()
print (np.concatenate((a,b),axis = 1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------------------------------
[[1 2 5 6]
 [3 4 7 8]]


### `numpy.stack(arrays, axis) `
沿**新轴**连接数组序列  
arrays相同形状的数组序列  
axis：插入一个纬度，插入方式类似`expand_dims()`，在这个插入的纬度上stack 

In [160]:
a = np.ones((2,3,4))
b = np.ones((2,3,4))
print(a.shape,b.shape)
c = np.stack((a,b,b,a,a),axis = 2)
print(c.shape)

(2, 3, 4) (2, 3, 4)
(2, 3, 5, 4)


### `numpy.hstack`

In [161]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
c = np.hstack((a,b))
print (c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### `numpy.vstack`

In [162]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
c = np.vstack((a,b))
print (c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 分割数组
函数|效果
---------|---------
split()	|将一个数组分割为多个子数组
array_split() | 将一个数组分割为多个子数组，不能除完，有余数也能分割
hsplit()	|将一个数组水平分割为多个子数组（按列）
vsplit()	|将一个数组垂直分割为多个子数组（按行）

### `numpy.split(ary, indices_or_sections, axis) ` 
ary：被分割的数组  
indices_or_sections：如果是一个整数，就用该数平均切分，不能平分就报错，如果是一个数组，为沿轴切分的位置（左开右闭）  
axis：是几，就把这个纬度的轴切了

In [21]:
a = np.arange(24).reshape(2,3,4)
b = np.split(a,3,axis = 1)
print (b)

[array([[[ 0,  1,  2,  3]],

       [[12, 13, 14, 15]]]), array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]]), array([[[ 8,  9, 10, 11]],

       [[20, 21, 22, 23]]])]


### `np.array_split(ary,3,axis)`不对称也能分割

In [20]:
a = np.arange(24).reshape(2,3,4)
print(np.array_split(a,3,axis = 2))

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]]), array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])]


### `numpy.hsplit` 相当于 np.split(axis = 1)

In [180]:
a = np.arange(24).reshape((2,3,4))
b = np.hsplit(a,3)
for x in b:
    print(x)
    print(x.shape)
    printline()

[[[ 0  1  2  3]]

 [[12 13 14 15]]]
(2, 1, 4)
-------------------------------------
[[[ 4  5  6  7]]

 [[16 17 18 19]]]
(2, 1, 4)
-------------------------------------
[[[ 8  9 10 11]]

 [[20 21 22 23]]]
(2, 1, 4)
-------------------------------------


### `numpy.vsplit` 相当于 np.split(axis = 0)

In [181]:
a = np.arange(20).reshape(4,5)
print (a)
printline()
b = np.vsplit(a,2)
for x in b:
    print (x)
    printline()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
-------------------------------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------


## 数组元素的添加与删除
函数|效果
--------|---------
resize()	|返回指定形状的新数组
append()	|将值添加到数组末尾
insert()	|沿指定轴将值插入到指定下标之前
delete()	|删掉某个轴的子数组，并返回删除后的新数组
unique()	|查找数组内的唯一元素

### `numpy.resize(arr, shape)`
返回指定大小的新数组。,如果新数组大小大于原始大小，则包含原始数组中的元素的副本。  

In [184]:
a = np.array([[1,2,3],[4,5,6]])
print (a)
print (a.shape)
printline()
b = np.resize(a, (3,2))
print (b)
print (b.shape)
printline()
b = np.resize(a,(5,3))
print (b)

[[1 2 3]
 [4 5 6]]
(2, 3)
-------------------------------------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
-------------------------------------
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]


### `numpy.append(arr, values, axis=None)`
类似`concatenate()`  
axis：默认为 None。**当axis无定义时，是横向加成，返回总是为一维数组**

In [191]:
a = np.ones((2,3,4))
print (a)
print (np.append(a, [7,8,9]))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 7. 8. 9.]


In [196]:
a = np.ones((2,3,4))
b = np.zeros((1,3,4))
print(np.append(a,b,axis = 0))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### `numpy.insert(arr, obj, values, axis)`
在给定索引之前，沿给定轴在输入数组中插入值。  
如果值的类型转换为要插入，则它与输入数组不同。 返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。  
arr：输入数组  
obj：在其之前插入值的索引  
values：要插入的值  
axis：沿着它插入的轴，如果未提供，则输入数组会被展开  

In [199]:
a = np.array([[1,2],[3,4],[5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.insert(a,3,[11,12]))
print ('\n')

print ('传递了 Axis 参数。 会广播值数组来配输入数组。') 
print ('沿轴 0 广播：')
print (np.insert(a,1,[11],axis = 0))
print ('\n')
 
print ('沿轴 1 广播：')
print (np.insert(a,1,11,axis = 1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


### `numpy.delete(arr, obj, axis)`
numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 
1. 与insert() 函数的情况一样，如果未提供轴参数，则输入数组将展开。  
2. 指定了axis，这个纬度中一个元素被删除了，整个这个纬度的一行都要被删除  

arr：输入数组  
obj：可以是切片，整数或者整数数组，表明要从输入数组删除的**子数组**  
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开

In [200]:
a = np.arange(12).reshape(3,4)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.delete(a,5))
print ('\n')
 
print ('删除第二列：')
print (np.delete(a,1,axis = 1))
print ('\n')
 
print ('包含从数组中删除的替代值的切片：')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print (np.delete(a, np.s_[::2]))

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


包含从数组中删除的替代值的切片：
[ 2  4  6  8 10]


### `numpy.unique(arr, return_index, return_inverse, return_counts)`
去除数组中的重复元素。  
arr：输入数组，如果不是一维数组则会展开  
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储  
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储  
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数

In [201]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
 
# 这里的索引就是 去重后数组相对于原来数组的索引
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
 

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]




In [202]:
print ('去重数组：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print ('\n')

# 这里的索引就是 去原来数组相对于去重数组的索引 
print ('下标为：')
print (indices)
print ('\n')
# 所以直接用 去重后的u，用 整数组 切片
print ('使用下标重构原数组：')
print (u[indices])
print ('\n')
 
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

去重数组：
[2 5 6 7 8 9]


下标为：
[1 0 2 0 3 1 2 4 0 5]


使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


# 8.算术函数

## 加减乘除: 
### `add()`，`subtract()`，`multiply()` 和 `divide()`


## 倒数
### `numpy.reciprocal()` 
函数返回参数逐元素的倒数。如 1/4 倒数为 4/1。


## 求幂
### `numpy.power()` 
函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。

In [5]:
a = np.array([10,100,1000])  
print (a)
b = np.array([1,2,3])  
print (np.power(a,b))

[  10  100 1000]
[        10      10000 1000000000]


## 取余
### `numpy.mod()` and  `numpy.remainder()` 
计算输入数组中相应元素的相除后的余数。 函数 

# 9.统计函数

### `numpy.amin()` 和 `numpy.amax()`
### `numpy.min()` 和 `numpy.max()`
### `numpy.argmin()` 和 `numpy.argmax()`

In [13]:
a = np.arange(12).reshape((3,4))
print(a)
printline()
print(np.amax(a,axis = 0))
printline()
print(np.amax(a,axis = 1))
printline()
print(np.amax(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------
[ 8  9 10 11]
-------------------------------------
[ 3  7 11]
-------------------------------------
11


### `numpy.percentile(a, q, axis)`
给你一个位置百分比，求出这个位置百分比的 准确值 是多少  
百分位数是统计中使用的度量，表示**小于**这个值的观察值的百分比。  
a: 输入数组  
q: 要计算的百分位数，在 0 ~ 100 之间  
axis: 沿着它计算百分位数的轴  

In [16]:
a = np.arange(12).reshape((3,4))
print(a)
printline()

print (np.percentile(a, 50))
printline()

print (np.percentile(a, 50, axis=0))
printline()

print (np.percentile(a, 50, axis=1))
printline()
# 保持维度不变
print (np.percentile(a, 50, axis=1, keepdims=True))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------
5.5
-------------------------------------
[4. 5. 6. 7.]
-------------------------------------
[1.5 5.5 9.5]
-------------------------------------
[[1.5]
 [5.5]
 [9.5]]


### `numpy.mean()` and `numpy.sum()`
算术平均值。 如果提供了轴，则沿其计算。  
算术平均值是沿轴的元素的总和除以元素的数量。

### `numpy.average()`
numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。  
权重需要是个一维的，可以是负数，但权重的和必须不为0   
该函数可以接受一个轴参数。 如果没有指定轴，则数组会被展开。   

In [32]:
a = np.arange(12).reshape((3,4))
b = np.array([1,1,1,-2])
np.average(a,weights = b,axis = 1)

array([-3.,  1.,  5.])

### `numpy.median()`
中位数（中值）

###  `numpy.std()`
标准差

###  `numpy.var()`
方差

### `numpy.cumsum(a)`叠加

In [6]:
a = np.arange(12).reshape((3,4))
print(np.cumsum(a))

[ 0  1  3  6 10 15 21 28 36 45 55 66]


### `numpy.diff(a)`差

In [7]:
a = np.arange(12).reshape((3,4))
print(np.diff(a))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# 10.排序、条件刷选函数

### `numpy.sort(a, axis, kind, order)` 从小到大
返回输入数组的排序副本  
a: 要排序的数组  
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着**最后的轴**排序
kind: 默认为'quicksort'（快速排序）  
order: 如果数组包含字段，则是要排序的字段

In [36]:
a = np.array([[2,7],[9,1]])  
print (a)
printline()
print (np.sort(a))
printline()
print (np.sort(a, axis =  1))
printline()
print (np.sort(a, axis =  0))
printline()

# 在 sort 函数中排序字段 
dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print ('我们的数组是：')
print (a)
print ('\n')
print ('按 name 排序：')
print (np.sort(a, order =  'name'))

[[2 7]
 [9 1]]
-------------------------------------
[[2 7]
 [1 9]]
-------------------------------------
[[2 7]
 [1 9]]
-------------------------------------
[[2 1]
 [9 7]]
-------------------------------------
我们的数组是：
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


按 name 排序：
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


### `numpy.argsort()` 从小到大
返回的是数组值从小到大的索引值。

In [37]:
x = np.array([3,  1,  2])  
print ('我们的数组是：')
print (x)
print ('\n')
print ('对 x 调用 argsort() 函数：')
y = np.argsort(x)  
print (y)
print ('\n')
print ('以排序后的顺序重构原数组：')
a = x[y]
print (a)
printline()
print(x)
print ('\n')
print ('使用循环 索引的方式 遍历 打印 排好序的数组：')
for i in y:  
    print (x[i], end=" ")


我们的数组是：
[3 1 2]


对 x 调用 argsort() 函数：
[1 2 0]


以排序后的顺序重构原数组：
[1 2 3]
-------------------------------------
[3 1 2]


使用循环 索引的方式 遍历 打印 排好序的数组：
1 2 3 

### `numpy.lexsort()`
numpy.lexsort() 用于对多个序列进行排序。排序时**优先照顾靠后的列**    
返回的是排好序的索引

In [287]:
nm =  ('raju','anil','ravi','amar') 
dv =  ('f.y.',  's.y.',  's.y.',  'f.y.') 
# 这里优先考虑nm列进行排序
ind1 = np.lexsort((nm,dv))  
# 这里优先考虑dv列进行排序
ind2 = np.lexsort((dv,nm)) 

print ('调用 lexsort() 函数：') 
print (ind1) 
print ('\n') 
print ('使用这个索引来获取排序后的数据：') 
print ([nm[i]  +  ", "  + dv[i]  for i in ind1])

print (ind2) 
print ('\n') 
print ('使用这个索引来获取排序后的数据：') 
print ([nm[i]  +  ", "  + dv[i]  for i in ind2])

调用 lexsort() 函数：
[3 0 1 2]


使用这个索引来获取排序后的数据：
['amar, f.y.', 'raju, f.y.', 'anil, s.y.', 'ravi, s.y.']
[3 1 0 2]


使用这个索引来获取排序后的数据：
['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']


### `np.msort()`
msort(a) 数组按第一个轴排序，返回排序后的数组副本。np.msort(a) 相等于 np.sort(a, axis=0)。

### ` np.sort_complex()`
对复数按照先实部后虚部的顺序进行排序。

### `np.partition(a, kth[, axis, kind, order]) `
指定一个数，对数组进行分区
1. 现将原数组排序
2. 找到排序后数组对应位置的数
3. 把原数组中小于这个数的放它的左边，大于等于的放右边
4. 也可以的一个一维数组，分成n个区
5. 只进行分区，每个区内部的大小，没有排过序

In [73]:
a = np.array([1, 10, 60, 40])
print(a)
printline()
# 将数组 a 中所有元素（包括重复元素）从小到大排列，变成 [1,10,40,60]
# 2 表示的是排序数组索引为 2 的数字，在这里就是40，比该数字小的排在该数字前面，比该数字大的排在该数字的后面
print(np.partition(a, 2))  
printline()
print(np.partition(a, (1, 2))) # 小于第1的在前面，大于第2个的在后面，即介于10和40


[ 1 10 60 40]
-------------------------------------
[ 1 10 40 60]
-------------------------------------
[ 1 10 40 60]


### `np.argpartition(a, kth[, axis, kind, order])`
可以通过关键字 kind 指定算法沿着指定轴对数组进行分区,返回的是 从小到大排好的值的索引  

In [64]:
arr = np.array([46, 57, 23, 230, 1, 10, 0, 120])
# 这里的2 表示，只把最小的前3找出来，与数组中 本来的前三互换位置，其他不管不动
a = np.argpartition(arr, 2)
print(a)

[6 4 5 3 1 2 0 7]


In [65]:
# 这里的-2 表示，只把最大的前2找出来（即-1，-2），与数组中 本来的 后二 的互换位置，其他不管不动
b = np.argpartition(arr, -2)
print(b)

[6 0 2 1 4 5 7 3]


In [66]:
# 同时找到第 3 和第 4 小的值。
c = arr[np.argpartition(arr,[1,2])[1]]
d = arr[np.argpartition(arr,[1,2])[2]]
print(c)
print(d)

1
10


### `numpy.argmax()` 和 `numpy.argmin()`
沿给定轴返回最大和最小元素的索引，不指定维度就展开,指定了就按指定的。

### `numpy.nonzero()`
返回输入数组中非零元素的索引，就一个参数，返回对应纬度数量的arrray，对应位置组合起来就是坐标

In [69]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]])  
print (a)
print (np.nonzero (a))

[[30 40  0]
 [ 0 20 10]
 [50  0 60]]
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


### `numpy.where()`
返回输入数组中满足给定条件的元素的索引。

In [71]:
x = np.arange(9.).reshape(3,  3)  
print (x)
printline()
y = np.where(x >  3)  
print (y)
printline()
# 重构数组，还有这一招
print (x[y])

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
-------------------------------------
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
-------------------------------------
[4. 5. 6. 7. 8.]


### `numpy.extract()`
根据某个条件从数组中抽取元素，返回满条件的元素。

In [72]:
x = np.arange(9.).reshape(3,  3)  
print (x)
# 定义条件, 选择偶数元素
condition = np.mod(x,2)  ==  0  
print ('按元素的条件值：')
print (condition)
print ('使用条件提取元素：')
print (np.extract(condition, x))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
按元素的条件值：
[[ True False  True]
 [False  True False]
 [ True False  True]]
使用条件提取元素：
[0. 2. 4. 6. 8.]


# 11.副本和视图
  

视图一般发生在：
1、numpy 的切片操作返回原数据的视图。  
2、调用 ndarray 的 view() 函数产生一个视图。  

副本一般发生在：
Python 序列的切片操作，调用deepCopy()函数。  
调用 ndarray 的 copy() 函数产生一个副本。

## 赋值引用，一个东西

In [74]:
a = np.ones((3,4))
b = a
print(id(a))
print(id(b))

4627113344
4627113344


## 视图

### `a.view()` 
创建一个新的数组对象，该方法创建的新数组的维数更改**不会更改原始数据的维数**。
修改值，**会更改原始数据的值**

In [77]:
a = np.arange(6).reshape(3,2)  
print ('数组 a：')
print (a)
print ('创建 a 的视图：')
b = a.view()  
print (b)
print ('两个数组的 id() 不同：')
print ('a 的 id()：')
print (id(a))
print ('b 的 id()：' )
print (id(b))
# 修改 b 的形状，并不会修改 a
b.shape =  2,3
print ('b 的形状：')
print (b)
print ('a 的形状：')
print (a)
# 修改值
print('值变了')
b[0][0] = 5
print(a)

数组 a：
[[0 1]
 [2 3]
 [4 5]]
创建 a 的视图：
[[0 1]
 [2 3]
 [4 5]]
两个数组的 id() 不同：
a 的 id()：
4627051104
b 的 id()：
4627051424
b 的形状：
[[0 1 2]
 [3 4 5]]
a 的形状：
[[0 1]
 [2 3]
 [4 5]]
值变了
[[5 1]
 [2 3]
 [4 5]]


## reshape，切片都是视图的一种
变量 a,b 都是 arr 的一部分视图，对视图的修改会直接反映到原数据中。但是我们观察 a,b 的 **id是不同的**。

In [78]:
arr = np.arange(12)
print ('我们的数组：')
print (arr)
print ('创建切片：')
a=arr[3:]
b=arr[3:]
a[1]=123
b[2]=234
print(arr)
print(id(a),id(b),id(arr[3:]))

我们的数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11]
创建切片：
[  0   1   2   3 123 234   6   7   8   9  10  11]
4627115584 4627051104 4627052464


## 副本或深拷贝


### `a.copy()` 函数创建一个副本。 对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置。

In [79]:
a = np.array([[10,10],  [2,3],  [4,5]])  
print ('数组 a：')
print (a)
print ('创建 a 的深层副本：')
b = a.copy()  
print ('数组 b：')
print (b)
# b 与 a 不共享任何内容  
print ('我们能够写入 b 来写入 a 吗？')
print (b is a)
print ('修改 b 的内容：')
b[0,0]  =  100  
print ('修改后的数组 b：')
print (b)
print ('a 保持不变：')
print (a)

数组 a：
[[10 10]
 [ 2  3]
 [ 4  5]]
创建 a 的深层副本：
数组 b：
[[10 10]
 [ 2  3]
 [ 4  5]]
我们能够写入 b 来写入 a 吗？
False
修改 b 的内容：
修改后的数组 b：
[[100  10]
 [  2   3]
 [  4   5]]
a 保持不变：
[[10 10]
 [ 2  3]
 [ 4  5]]


# 12.矩阵(Matrix)和线性代数

## 矩阵基本

### `matlib.empty(shape, dtype, order)`
shape: 定义新矩阵形状的整数或整数元组  
dtype: 可选，数据类型  
order: C（行序优先） 或者 F（列序优先）  

### `numpy.matlib.zeros()`
numpy.matlib.zeros() 函数创建一个以 0 填充的矩阵。

### `numpy.matlib.ones()`
numpy.matlib.ones()函数创建一个以 1 填充的矩阵。

### `numpy.matlib.eye(n, M,k, dtype)`
I矩阵
n: 返回矩阵的行数  
M: 返回矩阵的列数，默认为 n  
k: 对角线的索引  
dtype: 数据类型  

In [83]:
a = np.matlib.eye(3)
print(a)
printline()
b = np.matlib.eye(n =  3, M =  4, k =  0, dtype =  float)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### `numpy.matlib.identity()`
单位矩阵是个方阵，从左上角到右下角的对角线（称为主对角线）上的元素均为 1，除此以外全都为 0。

In [84]:
print (np.matlib.identity(5, dtype =  float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### `numpy.matlib.rand()`
numpy.matlib.rand() 函数创建一个给定大小的矩阵，数据是随机填充的。

In [85]:
print(np.matlib.rand(4,4))

[[1.56689826e-01 3.78570957e-01 7.63799021e-01 6.91025628e-01]
 [8.78459254e-01 2.86183431e-02 8.14539697e-01 5.56169172e-01]
 [4.16498958e-04 9.95545368e-01 2.06165697e-01 3.42285901e-01]
 [2.99473692e-01 8.65857537e-02 8.04009096e-01 1.13013950e-01]]


### `numpy.matrix()`

In [86]:
i = np.matrix('1,2;3,4')  
print (i)
print(type(i))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


### `numpy.asmatrix()`

In [87]:
a = [[1,2,3],[2,3,4]]
b = np.asarray(a)
c = np.asmatrix(b)  
print (c)
print(type(c))

[[1 2 3]
 [2 3 4]]
<class 'numpy.matrix'>


### `numpy.dot(a, b, out=None) `
dot	两个数组的点积 二维数组相当于 矩阵乘积  
a : ndarray 数组  
b : ndarray 数组  
out : ndarray, 可选，用来保存dot()的计算结果  

In [89]:
a = np.array([[1,2],[1,3]])
b = np.array([[3,5],[5,5]])
print(np.dot(a,b))

[[13 15]
 [18 20]]


### `numpy.vdot()`
numpy.vdot() 函数是两个向量的点积(对应位置乘积全部相加)。 如果第一个参数是复数，那么它的共轭复数会用于计算。 如果参数是多维数组，它会被展开。

In [90]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积
print (np.vdot(a,b))

130


$1*11 + 2*12 + 3*13 + 4*14 = 130$

### `numpy.inner()`
numpy.inner() 函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。

In [91]:
a = np.array([[1,2], [3,4]]) 
 
print ('数组 a：')
print (a)
b = np.array([[11, 12], [13, 14]]) 
 
print ('数组 b：')
print (b)
 
print ('内积：')
print (np.inner(a,b))

数组 a：
[[1 2]
 [3 4]]
数组 b：
[[11 12]
 [13 14]]
内积：
[[35 41]
 [81 95]]


1*11+2*12, 1*13+2*14 
3*11+4*12, 3*13+4*14

### `numpy.matmul`
numpy.matmul 函数返回两个数组的矩阵乘积。 虽然它返回二维数组的正常乘积，但如果任一参数的维数大于2，则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。

另一方面，如果任一参数是一维数组，则通过在其维度上附加 1 来将其提升为矩阵，并在乘法之后被去除。

对于二维数组，它就是矩阵乘法：

In [92]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [93]:
a = [[1,0],[0,1]] 
b = [1,2] 
print (np.matmul(a,b))
print (np.matmul(b,a))

[1 2]
[1 2]


In [94]:
a = np.arange(8).reshape(2,2,2) 
b = np.arange(4).reshape(2,2) 
print (np.matmul(a,b))

[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


### `@`点积

In [3]:
a = np.array([[1,2],[2,3]])
b = np.array([[2,3],[4,5]])
print(a@b)
print(a.dot(b))
print(np.matmul(a,b))

[[10 13]
 [16 21]]
[[10 13]
 [16 21]]
[[10 13]
 [16 21]]


### `np.transpose()` and `a.T`

In [22]:
a = np.arange(12).reshape((3,4))
print(a)
print(a.T)
print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### `np.clip(ary,v1,v2)`

In [24]:
a = np.arange(12).reshape((3,4))
print(a)
b = np.clip(a,3,6)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[3 3 3 3]
 [4 5 6 6]
 [6 6 6 6]]


## 函数库 linalg  
determinant	数组的行列式  
solve	求解线性矩阵方程  
inv	计算矩阵的乘法逆矩阵  

### `numpy.linalg.det()`
numpy.linalg.det() 函数计算输入矩阵的行列式。

In [96]:
a = np.array([[1,2], [3,4]]) 
print (np.linalg.det(a))

-2.0000000000000004


In [97]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print (b)
print (np.linalg.det(b))
print (6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


### `numpy.linalg.solve()`
numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解。

In [98]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
b = np.array([[6],[-4],[27]]) 
c = np.linalg.solve(a,b)
print(c)

[[ 5.]
 [ 3.]
 [-2.]]


### `numpy.linalg.inv()`
numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵。

逆矩阵（inverse matrix）：设A是数域上的一个n阶矩阵，若在相同数域上存在另一个n阶矩阵B，使得： AB=BA=E ，则我们称B是A的逆矩阵，而A则被称为可逆矩阵。注：E为单位矩阵。

In [95]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x)
print (y)
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# 13.提速
不管是1D/2D/3D 的 Array, 从根本上, 它都是一个 1D array!

In [9]:
col_major = np.zeros((10,10), order='C')    # C-type
row_major = np.zeros((10,10), order='F')    # Fortran

In [10]:
import time
a = np.zeros((200, 200), order='C')
b = np.zeros((200, 200), order='F')
N = 9999

def f1(a):
    for _ in range(N):
        np.concatenate((a, a), axis=0)

def f2(b):
    for _ in range(N):
        np.concatenate((b, b), axis=0)

t0 = time.time()
f1(a)
t1 = time.time()
f2(b)
t2 = time.time()

print((t1-t0)/N)     # 0.000040
print((t2-t1)/N)     # 0.000070

2.6845064076414965e-05
4.1490364627893455e-05


copy慢 view快

In [11]:
a_view1 = a[1:2, 3:6]    # 切片 slice
a_view2 = a[:100]        # 同上
a_view3 = a[::2]         # 跳步
a_view4 = a.ravel()      # 

In [12]:
a_copy1 = a[[1,4,6], [2,4,6]]   # 用 index 选
a_copy2 = a[[True, True], [False, True]]  # 用 mask
a_copy3 = a[[1,2], :]        # 虽然 1,2 的确连在一起了, 但是他们确实是 copy
a_copy4 = a[a[1,:] != 0, :]  # fancy indexing
a_copy5 = a[np.isnan(a), :]  # fancy indexing

IndexError: boolean index did not match indexed array along dimension 0; dimension is 200 but corresponding boolean dimension is 2

1.使用 np.take(), 替代用 index 选数据的方法.

上面提到了如果用index 来选数据, 像 a_copy1 = a[[1,4,6], [2,4,6]], 用 take 在大部分情况中会比这样的 a_copy1 要快.

In [13]:
a = np.random.rand(1000000, 10)
N = 99
indices = np.random.randint(0, 1000000, size=10000)

def f1(a):
    for _ in range(N):
        _ = np.take(a, indices, axis=0)

def f2(b):
    for _ in range(N):
        _ = b[indices]

print('%f' % ((t1-t0)/N))    # 0.000393
print('%f' % ((t2-t1)/N))    # 0.000569

0.002711
0.004191


2.使用 np.compress(), 替代用 mask 选数据的方法.

上面的 a_copy2 = a[[True, True], [False, True]] 这种就是用 TRUE, FALSE 来选择数据的. 测试如下:

In [14]:
mask = a[:, 0] < 0.5
def f1(a):
    for _ in range(N):
        _ = np.compress(mask, a, axis=0)

def f2(b):
    for _ in range(N):
        _ = b[mask]

print('%f' % ((t1-t0)/N))    # 0.028109
print('%f' % ((t2-t1)/N))    # 0.031013

0.002711
0.004191


out 参数
a=a+1 要先转换成 np.add() 这种形式再运算

In [15]:
a = a + 1         # 0.035230
a = np.add(a, 1)  # 0.032738

但是在功能里面有一个 out 参数, 让我们不必要重新创建一个 a. 所以下面两个是一样的功能, 都不会创建另一个 copy. 不过可能是上面提到的那个原因, 这里的运算时间也有差.

In [16]:
a += 1                 # 0.011219
np.add(a, 1, out=a)    # 0.008843

array([[4.10823238, 4.31999698, 4.30302507, ..., 4.68524769, 4.36370753,
        4.18183048],
       [4.19606708, 4.63684802, 4.2716437 , ..., 4.03748234, 4.80038643,
        4.03686822],
       [4.00376311, 4.02205258, 4.22616049, ..., 4.01416798, 4.335893  ,
        4.6886139 ],
       ...,
       [4.83433011, 4.32098196, 4.11229323, ..., 4.44101614, 4.1270659 ,
        4.0718922 ],
       [4.21081382, 4.91660073, 4.65475811, ..., 4.66810681, 4.52927175,
        4.55064592],
       [4.17899507, 4.80235101, 4.11546945, ..., 4.7188631 , 4.4007728 ,
        4.45255584]])