# 对位各种运算符算，有一维一样就能广播
# 很多统计方法，没指定维数就是展开全部，指定了就按指定的算

# 数据类型

In [1]:
def printline():
    print("-------------------------------------")

In [2]:
import numpy as np
student = np.dtype([('name','S10'),('age','i1')])
d_student = np.array([('Mary',20),('Tom',22)])
print(d_student)

[['Mary' '20']
 ['Tom' '22']]


In [3]:
d_student = np.array([('Mary',20),('Tom',22)],dtype = student)
print(d_student)

[(b'Mary', 20) (b'Tom', 22)]


# 数组属性

In [4]:
print(d_student.ndim)

1


In [18]:
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


In [23]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
c = b.reshape(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


每列对不上的话，不显示另外的一个

In [29]:
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)
a = np.array([[1,2,3,6,9],[4,5,6]])  
print (a.shape)


(2, 3)
(2,)


In [37]:
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


# 创建数组

## numpy.empty(shape, dtype = float, order = 'C')

In [48]:
y = np.empty([3,2], dtype = int) 
# 数组元素为随机值，因为它们未初始化。
print (y)

[[0 0]
 [0 0]
 [0 0]]


## numpy.zeros(shape, dtype = float, order = 'C')

In [50]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [53]:
x = np.zeros((2,2),dtype = int)
print(x)

[[0 0]
 [0 0]]


In [60]:
x = np.zeros((3,3),dtype = [('x',int),('y',int)])
print(x)

[[(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]]


## numpy.ones(shape, dtype = None, order = 'C')

## numpy.asarray(a, dtype = None, order = None)

In [61]:
x = [1,2,3,4]
a= np.asarray(x)
print(a)

[1 2 3 4]


In [62]:
x = (3,4,5,6,7)
a = np.asarray(x)
print(a)

[3 4 5 6 7]


In [63]:
x = [[1,2,4],[4,5,6]]
a = np.asarray(x)
print(a)

[[1 2 4]
 [4 5 6]]


In [64]:
x = [[1,2,4],[4,5,6]]
a = np.asarray(x,dtype=float)
print(a)

[[1. 2. 4.]
 [4. 5. 6.]]


## numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)

注意：buffer 是字符串的时候，Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b

buffer	可以是任意对象，会以流的形式读入。  
dtype	返回数组的数据类型，可选  
count	读取的数据数量，默认为-1，读取所有数据。  
offset	读取的起始位置，默认为0。  

In [67]:
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


## numpy.fromiter(iterable, dtype, count=-1)

In [70]:
list=range(4)
it=iter(list)
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3.]


In [ ]:
a = x.reshape(2,2)
print(a)

## numpy.arange(start, stop, step, dtype)

start	起始值，默认为0  
stop	终止值（不包含）  
step	步长，默认为1  
dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。  

In [73]:
a = np.arange(5,20,2,int)
print(a)

[ 5  7  9 11 13 15 17 19]


In [75]:
print(a.reshape(2,4))

[[ 5  7  9 11]
 [13 15 17 19]]


## np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start	序列的起始值  
stop	序列的终止值，如果endpoint为true，该值包含于数列中  
num	要生成的等步长的样本数量，默认为50  
endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。  
retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。  
dtype	ndarray 的数据类型  

In [77]:
a =np.linspace(1,10,10,retstep= True)
print(a)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


## np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

start	序列的起始值为：base ** start  
stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中  
num	要生成的等步长的样本数量，默认为50  
endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。  
base	对数 log 的底数。  
dtype	ndarray 的数据类型  

In [85]:
a = np.logspace(1,2,num = 10, base = 2, dtype = float)
print(a)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]


## Numpy 创建标准正态分布数组

randint([low,high],size)

In [126]:
a=np.random.randn(2,3)
print(a)
print("----------------------")
a=np.random.randint(100,200,(3,3))
print(a)

[[-0.29476028  0.37918896  0.90067023]
 [ 0.34452946  0.67063866 -2.9054671 ]]
----------------------
[[111 106 109]
 [145 190 195]
 [118 178 193]]


# NumPy 切片和索引

In [88]:
a = np.arange(10)
print(a)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]


冒号 : 的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。

In [90]:
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
b = a[5] 
print(b)
print(a[2:])

5
[2 3 4 5 6 7 8 9]


In [91]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]


切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。
省略号表示：全部

In [92]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素，相当于：全部行的第2列
print (a[1,...])   # 第2行元素，相当于：第2行的全部列
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


## 整数数组索引

In [98]:
# 数组中(0,0)，(1,1)和(2,0)位置处的元素
# ([0,1,2]) 代表 行数  [0,1,0] 代表列数
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
print(x)
print("----------------------")
# 切片中 [a,b] a,b分别代表行，列 可以是 省略号，切片，指定的整数数组
y = x[[0,1,2],  [0,1,0]]  
print (y)
print("----------------------")
y = x[...,1:]
print(y)
print("----------------------")
y = x[...,0:1]
print(y)
print("----------------------")
y = x[0:2,...]
print(y)

[[1 2]
 [3 4]
 [5 6]]
----------------------
[1 4 5]
----------------------
[[2]
 [4]
 [6]]
----------------------
[[1]
 [3]
 [5]]
----------------------
[[1 2]
 [3 4]]


# 布尔索引

In [99]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


## 花式索引

对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。

In [103]:
x=np.arange(32).reshape((8,4))
print(x)
print("----------------------")
# 这里的4，2，1，7就是行的标号
print (x[[4,2,1,7]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
----------------------
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


In [122]:
x = np.arange(32).reshape(1,32)
print(x)
print("----------------------")
print(x[[0]])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]]
----------------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]]


In [123]:
x = np.array([1,2,3,4])
print(x)
print(x.reshape(1,4))
print("----------------------")
print(x[[0]])

[1 2 3 4]
[[1 2 3 4]]
----------------------
[1]


# NumPy 广播(Broadcast)

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。
就是如果其中一个是一条边，那就能把它扩展成一个面

In [127]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [134]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


4x3 的二维数组与长为 3 的一维数组相加，等效于把数组 b 在二维上重复 4 次再运算：

In [129]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))
print(a + bb)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [135]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a*b)

[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


In [149]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,22,20],
           [30,30,30]])
b = np.array([[1],[2],[3],[4]])
print(a*b)

[[  0   0   0]
 [ 20  20  20]
 [ 60  66  60]
 [120 120 120]]


# NumPy 迭代数组

In [159]:
a = np.arange(8).reshape(2,4)
print(a)
printline()
for x in np.nditer(a):
    print(x,end=" ")
    

[[0 1 2 3]
 [4 5 6 7]]
-------------------------------------
0 1 2 3 4 5 6 7 

遍历默认是内存布局顺序，所以即使T一下也一样

In [162]:
print(a.T)
for x in np.nditer(a.T):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
0 1 2 3 4 5 6 7 

复制一下，新存一个就不一样了,内存状态为 04152637，复制的时候默认是按行访问 即order=‘C’

In [161]:
b = a.T.copy(order = 'C')
print(b)
printline()
for x in np.nditer(b):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
-------------------------------------
0 4 1 5 2 6 3 7 

In [163]:
b = a.T.copy()
print(b)
printline()
for x in np.nditer(b):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
-------------------------------------
0 4 1 5 2 6 3 7 

In [164]:
b = a.T.copy(order = 'F')
print(b)
printline()
for x in np.nditer(b):
    print(x,end=" ")

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
-------------------------------------
0 1 2 3 4 5 6 7 

可以通过显式设置，来强制 nditer 对象使用某种顺序：

In [165]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('以 C 风格顺序排序：')
for x in np.nditer(a, order =  'C'):  
    print (x, end=", " )
print ('\n')
print ('以 F 风格顺序排序：')
for x in np.nditer(a, order =  'F'):  
    print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


以 C 风格顺序排序：
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

以 F 风格顺序排序：
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

## 修改数组中元素的值
nditer 对象有另一个可选参数 op_flags。 默认情况下，nditer 将视待迭代遍历的数组为只读对象（read-only），为了在遍历数组的同时，实现对数组元素值得修改，必须指定 read-write 或者 write-only 的模式。

In [173]:
a = np.arange(20).reshape(4,5)
print(a)
printline()
for x in np.nditer(a,op_flags = ['readwrite']):
    x[...]=x*2
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


## 使用外部循环  
c_index	可以跟踪 C 顺序的索引  
f_index	可以跟踪 Fortran 顺序的索引  
multi-index	每次迭代可以跟踪一种索引类型  
external_loop	给出的值是具有多个值的一维数组，而不是零维数组  

In [175]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('修改后的数组是：')
for x in np.nditer(a, flags =  ['external_loop'], order =  'F'):  
   print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[ 0 20 40], [ 5 25 45], [10 30 50], [15 35 55], 

## 广播迭代

In [176]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

# Numpy 数组操作

## 修改数组形状
reshape	不改变数据的条件下修改形状  
flat	数组元素迭代器  
flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组  
ravel	返回展开数组  

### numpy.reshape(arr, newshape, order='C')

### numpy.ndarray.flat  
numpy.ndarray.flat 是一个数组元素迭代器，实例如下:

In [192]:
a = np.arange(9).reshape(3,3) 
print ('原始数组：')
for row in a:
    print (row)
 
# 对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print ('迭代后的数组：')
for element in a.flat:
    print (element)

原始数组：
[0 1 2]
[3 4 5]
[6 7 8]
迭代后的数组：
0
1
2
3
4
5
6
7
8


### numpy.ndarray.flatten
numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：  
ndarray.flatten(order='C')
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序

In [193]:
a = np.arange(20).reshape(4,5)
print(a)
printline()
print(a.flatten(order ="C"))
printline()
print(a.flatten(order ="F"))
printline()
print(a.flatten(order ="A"))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
-------------------------------------
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]
-------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### numpy.ravel
numpy.ravel(a, order='C')
numpy.ravel() 展平的数组元素，顺序通常是"C风格"，返回的是数组视图（view，有点类似 C/C++引用reference的意味），修改会影响原始数组。

In [194]:
a = np.arange(20).reshape(4,5)
print(a)
printline()
print(a.ravel(order = "F"))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------------------------
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [195]:
np.ravel(a,order = 'F')


array([ 0,  5, 10, 15,  1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,
        9, 14, 19])

## 翻转数组
transpose	对换数组的维度  
ndarray.T	和 self.transpose() 相同  
rollaxis	向后滚动指定的轴  
swapaxes	对换数组的两个轴  

In [200]:
a = np.arange(12).reshape(3,4)
print(a)
printline()
print(a.T)
printline()
print(a.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
-------------------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### numpy.rollaxis
numpy.rollaxis 函数向后滚动特定的轴到一个特定位置，格式如下：

numpy.rollaxis(arr, axis, start)  
参数说明： 
arr：数组
axis：要向后滚动的轴，其它轴的相对位置不会改变  
start：默认为零，表示完整的滚动。会滚动到特定位置。  

In [201]:
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('\n')
# 将轴 2 滚动到轴 0（宽度到深度）
 
print ('调用 rollaxis 函数：')
print (np.rollaxis(a,2))
# 将轴 0 滚动到轴 1：（宽度到高度）
print ('\n')
 
print ('调用 rollaxis 函数：')
print (np.rollaxis(a,2,1))

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


调用 rollaxis 函数：
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


调用 rollaxis 函数：
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


### numpy.swapaxes
numpy.swapaxes 函数用于交换数组的两个轴，格式如下： 
numpy.swapaxes(arr, axis1, axis2)  
arr：输入的数组  
axis1：对应第一个轴的整数  
axis2：对应第二个轴的整数  


In [202]:
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('\n')
# 现在交换轴 0（深度方向）到轴 2（宽度方向）
 
print ('调用 swapaxes 函数后的数组：')
print (np.swapaxes(a, 2, 0))

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


调用 swapaxes 函数后的数组：
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


## 修改数组维度
broadcast	产生模仿广播的对象  
broadcast_to	将数组广播到新形状  
expand_dims	扩展数组的形状  
squeeze	从数组的形状中删除一维条目  

In [219]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6]) 
# 对 y 广播 x
b = np.broadcast(x,y) 
# b拥有 iterator 属性，基于自身组件的迭代器元组
print(b)
r,c = b.iters
print (next(r), next(c))
print (next(r), next(c))
print (next(r), next(c))
print (next(r), next(c))

print ('广播对象的形状：')
print (b.shape)
print ('\n')
# 手动使用 broadcast 将 x 与 y 相加
b = np.broadcast(x,y)
c = np.empty(b.shape)
 
print ('手动使用 broadcast 将 x 与 y 相加：')
print (c.shape)
print ('\n')
c.flat = [u + v for (u,v) in b]
 
print ('调用 flat 函数：')
print (c)
print ('\n')
# 获得了和 NumPy 内建的广播支持相同的结果
 
print ('x 与 y 的和：')
print (x + y)


1 4
1 5
1 6
2 4
广播对象的形状：
(3, 3)


手动使用 broadcast 将 x 与 y 相加：
(3, 3)


调用 flat 函数：
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


x 与 y 的和：
[[5 6 7]
 [6 7 8]
 [7 8 9]]


### numpy.broadcast_to
numpy.broadcast_to 函数将数组广播到新形状。它在原始数组上返回只读视图。 它通常不连续。 如果新形状不符合 NumPy 的广播规则，该函数可能会抛出ValueError.

numpy.broadcast_to(array, shape, subok)  

In [220]:
a = np.arange(4).reshape(1,4)
 
print ('原数组：')
print (a)
print ('\n')
 
print ('调用 broadcast_to 函数之后：')
print (np.broadcast_to(a,(4,4)))

原数组：
[[0 1 2 3]]


调用 broadcast_to 函数之后：
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


### numpy.expand_dims
numpy.expand_dims 函数通过在指定位置插入新的轴来扩展数组形状，函数格式如下:

numpy.expand_dims(arr, axis)  
arr：输入数组  
axis：新轴插入的位置  

In [221]:
x = np.array(([1,2],[3,4]))
 
print ('数组 x：')
print (x)
print ('\n')
y = np.expand_dims(x, axis = 0)
 
print ('数组 y：')
print (y)
print ('\n')
 
print ('数组 x 和 y 的形状：')
print (x.shape, y.shape)
print ('\n')
# 在位置 1 插入轴
y = np.expand_dims(x, axis = 1)
 
print ('在位置 1 插入轴之后的数组 y：')
print (y)
print ('\n')
 
print ('x.ndim 和 y.ndim：')
print (x.ndim,y.ndim)
print ('\n')
 
print ('x.shape 和 y.shape：')
print (x.shape, y.shape)

数组 x：
[[1 2]
 [3 4]]


数组 y：
[[[1 2]
  [3 4]]]


数组 x 和 y 的形状：
(2, 2) (1, 2, 2)


在位置 1 插入轴之后的数组 y：
[[[1 2]]

 [[3 4]]]


x.ndim 和 y.ndim：
2 3


x.shape 和 y.shape：
(2, 2) (2, 1, 2)


### numpy.squeeze
numpy.squeeze 函数从给定数组的形状中删除一维的条目，函数格式如下：

numpy.squeeze(arr, axis)

参数说明：  
arr：输入数组  
axis：整数或整数元组，用于选择形状中一维条目的子集  

In [222]:
x = np.arange(9).reshape(1,3,3)
 
print ('数组 x：')
print (x)
print ('\n')
y = np.squeeze(x)
 
print ('数组 y：')
print (y)
print ('\n')
 
print ('数组 x 和 y 的形状：')
print (x.shape, y.shape)

数组 x：
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


数组 y：
[[0 1 2]
 [3 4 5]
 [6 7 8]]


数组 x 和 y 的形状：
(1, 3, 3) (3, 3)


## 连接数组
concatenate	连接沿现有轴的数组序列  
stack	沿着新的轴加入一系列数组  
hstack	水平堆叠序列中的数组（列方向）  
vstack	竖直堆叠序列中的数组（行方向）  

### numpy.concatenate
numpy.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组，格式如下：  
numpy.concatenate((a1, a2, ...), axis)  
a1, a2, ...：相同类型的数组  
axis：沿着它连接数组的轴，默认为 0


In [223]:
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
# 两个数组的维度相同
 
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b)))
print ('\n')
 
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


### numpy.stack
numpy.stack 函数用于沿新轴连接数组序列，格式如下：  
numpy.stack(arrays, axis)  

参数说明：  
arrays相同形状的数组序列  
axis：返回数组中的轴，输入数组沿着它来堆叠  

In [224]:
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('沿轴 0 堆叠两个数组：')
print (np.stack((a,b),0))
print ('\n')
 
print ('沿轴 1 堆叠两个数组：')
print (np.stack((a,b),1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### numpy.hstack

In [225]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('水平堆叠：')
c = np.hstack((a,b))
print (c)
print ('\n')

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


水平堆叠：
[[1 2 5 6]
 [3 4 7 8]]




### numpy.vstack

In [226]:

a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('竖直堆叠：')
c = np.vstack((a,b))
print (c)

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


竖直堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 分割数组
split	将一个数组分割为多个子数组  
hsplit	将一个数组水平分割为多个子数组（按列）  
vsplit	将一个数组垂直分割为多个子数组（按行）  

### numpy.split
numpy.split 函数沿特定的轴将数组分割为子数组，格式如下：  
numpy.split(ary, indices_or_sections, axis) 

参数说明：  
ary：被分割的数组  
indices_or_sections：果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）  
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分  

In [227]:
a = np.arange(9)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print (b)
print ('\n')
 
print ('将数组在一维数组中表明的位置分割：')
b = np.split(a,[4,7])
print (b)

第一个数组：
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


### numpy.hsplit

In [232]:
harr = np.floor(10 * np.random.random((2, 6)))
print ('原array：')
print(harr)
 
print ('拆分后：')
b = np.hsplit(harr, 3)
for x in b:
    print(x)
    printline()

原array：
[[8. 6. 3. 9. 2. 6.]
 [5. 7. 8. 4. 1. 1.]]
拆分后：
[[8. 6.]
 [5. 7.]]
-------------------------------------
[[3. 9.]
 [8. 4.]]
-------------------------------------
[[2. 6.]
 [1. 1.]]
-------------------------------------


### numpy.vsplit

In [231]:
a = np.arange(16).reshape(4,4)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('竖直分割：')
b = np.vsplit(a,2)
for x in b:
    print (x)
    printline()

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[[0 1 2 3]
 [4 5 6 7]]
-------------------------------------
[[ 8  9 10 11]
 [12 13 14 15]]
-------------------------------------


## 数组元素的添加与删除
resize	返回指定形状的新数组  
append	将值添加到数组末尾  
insert	沿指定轴将值插入到指定下标之前  
delete	删掉某个轴的子数组，并返回删除后的新数组  
unique	查找数组内的唯一元素  

### numpy.resize
numpy.resize 函数返回指定大小的新数组。  
如果新数组大小大于原始大小，则包含原始数组中的元素的副本。  
numpy.resize(arr, shape)

参数说明： 
arr：要修改大小的数组  
shape：返回数组的新形状  

In [235]:
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的形状：')
print (a.shape)
print ('\n')
b = np.resize(a, (3,2))
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('第二个数组的形状：')
print (b.shape)
print ('\n')

# 要注意 a 的第一行在 b 中重复出现，因为尺寸变大了 
print ('修改第二个数组的大小：')
b = np.resize(a,(5,3))
print (b)

第一个数组：
[[1 2 3]
 [4 5 6]]


第一个数组的形状：
(2, 3)


第二个数组：
[[1 2]
 [3 4]
 [5 6]]


第二个数组的形状：
(3, 2)


修改第二个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]


### numpy.append
numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。 此外，输入数组的维度必须匹配否则将生成ValueError。

append 函数返回的始终是一个一维数组。

numpy.append(arr, values, axis=None)

参数说明：

arr：输入数组
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）  
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，分别为0和1的时候。当axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。

In [236]:
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')
 
print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')
 
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### numpy.insert
numpy.insert 函数在给定索引之前，沿给定轴在输入数组中插入值。

如果值的类型转换为要插入，则它与输入数组不同。 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

numpy.insert(arr, obj, values, axis)

参数说明：

arr：输入数组  
obj：在其之前插入值的索引  
values：要插入的值  
axis：沿着它插入的轴，如果未提供，则输入数组会被展开  


In [238]:
a = np.array([[1,2],[3,4],[5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.insert(a,3,[11,12]))
print ('\n')

print ('传递了 Axis 参数。 会广播值数组来配输入数组。') 
print ('沿轴 0 广播：')
print (np.insert(a,1,[11],axis = 0))
print ('\n')
 
print ('沿轴 1 广播：')
print (np.insert(a,1,11,axis = 1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


### numpy.delete
numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，如果未提供轴参数，则输入数组将展开。

Numpy.delete(arr, obj, axis)

参数说明：

arr：输入数组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组  
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开

In [239]:
a = np.arange(12).reshape(3,4)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.delete(a,5))
print ('\n')
 
print ('删除第二列：')
print (np.delete(a,1,axis = 1))
print ('\n')
 
print ('包含从数组中删除的替代值的切片：')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print (np.delete(a, np.s_[::2]))

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


包含从数组中删除的替代值的切片：
[ 2  4  6  8 10]


### numpy.unique
numpy.unique 函数用于去除数组中的重复元素。

numpy.unique(arr, return_index, return_inverse, return_counts)

arr：输入数组，如果不是一维数组则会展开  
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储  
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储  
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数

In [246]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
 
# 这里的索引就是 去重后数组相对于原来数组的索引
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
 

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]




In [247]:
print ('去重数组：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print ('\n')

# 这里的索引就是 去原来数组相对于去重数组的索引 
print ('下标为：')
print (indices)
print ('\n')
# 所以直接用 去重后的u，用 整数组 切片
print ('使用下标重构原数组：')
print (u[indices])
print ('\n')
 
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

去重数组：
[2 5 6 7 8 9]


下标为：
[1 0 2 0 3 1 2 4 0 5]


使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


# NumPy 算术函数
## 加减乘除: 
add()，subtract()，multiply() 和 divide()
## 倒数
numpy.reciprocal() 函数返回参数逐元素的倒数。如 1/4 倒数为 4/1。
## 求幂
numpy.power() 函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。

In [262]:
a = np.array([10,100,1000])  

print (a)
printline()
print (np.power(a,2))
printline()
b = np.array([1,2,3])  
print (b)
printline()
print (np.power(a,b))

[  10  100 1000]
-------------------------------------
[    100   10000 1000000]
-------------------------------------
[1 2 3]
-------------------------------------
[        10      10000 1000000000]


## 取余
numpy.mod() 计算输入数组中相应元素的相除后的余数。 函数 numpy.remainder() 也产生相同的结果。

# NumPy 统计函数
## numpy.amin() 和 numpy.amax()
numpy.amin() 用于计算数组中的元素沿指定轴的最小值。

numpy.amax() 用于计算数组中的元素沿指定轴的最大值。

In [268]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print ('我们的数组是：')
print (a)
print ('\n')
# 1维就是横的
print ('调用 amin() 函数：')
print (np.amin(a))
print ('\n')
print (np.amin(a,1))
print ('\n')

# 0维就是竖的
print ('再次调用 amin() 函数：')
print (np.amin(a,0))
print ('\n')
# 不指定维数，就是展开全部求最大最小
print ('调用 amax() 函数：')
print (np.amax(a))
print ('\n')
print ('再次调用 amax() 函数：')
print (np.amax(a, axis =  0))

我们的数组是：
[[3 7 5]
 [8 4 3]
 [2 4 9]]


调用 amin() 函数：
2


[3 3 2]


再次调用 amin() 函数：
[2 4 3]


调用 amax() 函数：
9


再次调用 amax() 函数：
[8 7 9]


## numpy.percentile()
给你一个位置百分比，求出这个位置百分比的 准确值 是多少  
百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。 函数numpy.percentile()接受以下参数。

numpy.percentile(a, q, axis)


参数说明：

a: 输入数组  
q: 要计算的百分位数，在 0 ~ 100 之间  
axis: 沿着它计算百分位数的轴  

In [269]:
a = np.array([[10, 7, 4], [3, 2, 1]])
print ('我们的数组是：')
print (a)
 
print ('调用 percentile() 函数：')
# 50% 的分位数，就是 a 里排序之后的中位数
print (np.percentile(a, 50)) 
 
# axis 为 0，在纵列上求
print (np.percentile(a, 50, axis=0)) 
 
# axis 为 1，在横行上求
print (np.percentile(a, 50, axis=1)) 
 
# 保持维度不变
print (np.percentile(a, 50, axis=1, keepdims=True))

我们的数组是：
[[10  7  4]
 [ 3  2  1]]
调用 percentile() 函数：
3.5
[6.5 4.5 2.5]
[7. 2.]
[[7.]
 [2.]]


## numpy.median()
numpy.median() 函数用于计算数组 a 中元素的中位数（中值）
## numpy.mean()
numpy.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。

算术平均值是沿轴的元素的总和除以元素的数量。
## numpy.average()
numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。

该函数可以接受一个轴参数。 如果没有指定轴，则数组会被展开。

在多维数组中，可以指定用于计算的轴。

In [271]:
a = np.array([1,2,3,4])  
print ('我们的数组是：')
print (a)
print ('\n')
# 不指定权重时相当于 mean 函数
print ('调用 average() 函数：')
print (np.average(a))
print ('\n')

wts = np.array([4,3,2,1])  
print ('加权调用 average() 函数：')
print (np.average(a,weights = wts))
print ('\n')
# 如果 returned 参数设为 true，则返回权重的和  
print ('权重的和：')
print (np.average([1,2,3,  4],weights =  [4,3,2,1], returned =  True))

我们的数组是：
[1 2 3 4]


调用 average() 函数：
2.5


加权调用 average() 函数：
2.0


权重的和：
(2.0, 10.0)


## 标准差 numpy.std()
## 方差 numpy.var()

# NumPy 排序、条件刷选函数

## numpy.sort()
numpy.sort() 函数返回输入数组的排序副本。函数格式如下：

numpy.sort(a, axis, kind, order)

参数说明：

a: 要排序的数组  
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序， axis=0 按列排序，axis=1 按行排序  
kind: 默认为'quicksort'（快速排序）  
order: 如果数组包含字段，则是要排序的字段

In [278]:
a = np.array([[2,7],[9,1]])  
print ('原始数组是：')
print (a)
print ('\n')

print ('原始按行排序：')
print (np.sort(a, axis =  1))
print ('\n')

print ('原始按列排序：')
print (np.sort(a, axis =  0))
print ('\n')



print ('调用 sort() 函数：')
print (np.sort(a))
print ('\n')



# 在 sort 函数中排序字段 
dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print ('我们的数组是：')
print (a)
print ('\n')
print ('按 name 排序：')
print (np.sort(a, order =  'name'))

原始数组是：
[[2 7]
 [9 1]]


原始按行排序：
[[2 7]
 [1 9]]


原始按列排序：
[[2 1]
 [9 7]]


调用 sort() 函数：
[[2 7]
 [1 9]]


我们的数组是：
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


按 name 排序：
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


## numpy.argsort()
numpy.argsort() 函数返回的是数组值从小到大的索引值。

In [283]:
x = np.array([3,  1,  2])  
print ('我们的数组是：')
print (x)
print ('\n')
print ('对 x 调用 argsort() 函数：')
y = np.argsort(x)  
print (y)
print ('\n')
print ('以排序后的顺序重构原数组：')
a = x[y]
print (a)
printline()
print(x)
print ('\n')
print ('使用循环 索引的方式 遍历 打印 排好序的数组：')
for i in y:  
    print (x[i], end=" ")


我们的数组是：
[3 1 2]


对 x 调用 argsort() 函数：
[1 2 0]


以排序后的顺序重构原数组：
[1 2 3]
-------------------------------------
[3 1 2]


使用循环 索引的方式 遍历 打印 排好序的数组：
1 2 3 

## numpy.lexsort()
numpy.lexsort() 用于对多个序列进行排序。把它想象成对电子表格进行排序，每一列代表一个序列，排序时优先照顾靠后的列。  
返回的是排好序的索引

In [287]:
nm =  ('raju','anil','ravi','amar') 
dv =  ('f.y.',  's.y.',  's.y.',  'f.y.') 
# 这里优先考虑nm列进行排序
ind1 = np.lexsort((nm,dv))  
# 这里优先考虑dv列进行排序
ind2 = np.lexsort((dv,nm)) 

print ('调用 lexsort() 函数：') 
print (ind1) 
print ('\n') 
print ('使用这个索引来获取排序后的数据：') 
print ([nm[i]  +  ", "  + dv[i]  for i in ind1])

print (ind2) 
print ('\n') 
print ('使用这个索引来获取排序后的数据：') 
print ([nm[i]  +  ", "  + dv[i]  for i in ind2])

调用 lexsort() 函数：
[3 0 1 2]


使用这个索引来获取排序后的数据：
['amar, f.y.', 'raju, f.y.', 'anil, s.y.', 'ravi, s.y.']
[3 1 0 2]


使用这个索引来获取排序后的数据：
['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']


## msort、sort_complex、partition、argpartition
msort(a) 数组按第一个轴排序，返回排序后的数组副本。np.msort(a) 相等于 np.sort(a, axis=0)。  
sort_complex(a) 对复数按照先实部后虚部的顺序进行排序。  
partition(a, kth[, axis, kind, order]) 指定一个数，对数组进行分区  

argpartition(a, kth[, axis, kind, order]) 可以通过关键字 kind 指定算法沿着指定轴对数组进行分区   
返回的是 从小到大排好的值的 索引  

In [302]:
arr = np.array([46, 57, 23, 230, 1, 10, 0, 120])
# 这里的2 表示，只把最小的前3找出来，与数组中 本来的前三互换位置，其他不管不动
a = np.argpartition(arr, 2)
print(a)

[6 4 5 3 1 2 0 7]


In [304]:
# 这里的-2 表示，只把最大的前2找出来（即-1，-2），与数组中 本来的 后二 的互换位置，其他不管不动
b = np.argpartition(arr, -2)
print(b)

[6 0 2 1 4 5 7 3]


In [307]:
# 同时找到第 3 和第 4 小的值。
c = arr[np.argpartition(arr,[1,2])[1]]
d = arr[np.argpartition(arr,[1,2])[2]]
print(c)
print(d)

1
10


## numpy.argmax() 和 numpy.argmin()
numpy.argmax() 和 numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引。
不指定 维度 就展开  
指定了就按指定的  
np.argmax(a, axis =  0)  

## numpy.nonzero()
numpy.nonzero() 函数返回输入数组中非零元素的索引。
不指定维度，直接给两个

In [308]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]])  
print ('我们的数组是：')
print (a)
print ('\n')
print ('调用 nonzero() 函数：')
print (np.nonzero (a))

我们的数组是：
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]


调用 nonzero() 函数：
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


结果第一个相当于是 axis=0，第二个是相当于市 axis=1

## numpy.where()
numpy.where() 函数返回输入数组中满足给定条件的元素的索引。

In [309]:
x = np.arange(9.).reshape(3,  3)  
print ('我们的数组是：')
print (x)
print ( '大于 3 的元素的索引：')
y = np.where(x >  3)  
print (y)
print ('使用这些索引来获取满足条件的元素：')
print (x[y])

我们的数组是：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
大于 3 的元素的索引：
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
使用这些索引来获取满足条件的元素：
[4. 5. 6. 7. 8.]


## numpy.extract()
numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。

In [4]:
x = np.arange(9.).reshape(3,  3)  
print ('我们的数组是：')
print (x)
# 定义条件, 选择偶数元素
condition = np.mod(x,2)  ==  0  
print ('按元素的条件值：')
print (condition)
print ('使用条件提取元素：')
print (np.extract(condition, x))

我们的数组是：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
按元素的条件值：
[[ True False  True]
 [False  True False]
 [ True False  True]]
使用条件提取元素：
[0. 2. 4. 6. 8.]


# NumPy 副本和视图
副本是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同一位置。

视图是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。如果我们对视图进行修改，它会影响到原始数据，物理内存在同一位置。

视图一般发生在：
1、numpy 的切片操作返回原数据的视图。  
2、调用 ndarray 的 view() 函数产生一个视图。  

副本一般发生在：
Python 序列的切片操作，调用deepCopy()函数。  
调用 ndarray 的 copy() 函数产生一个副本。  

## 无复制

In [5]:
a = np.arange(6)  
print ('我们的数组是：')
print (a)
print ('调用 id() 函数：')
print (id(a))
print ('a 赋值给 b：')
b = a 
print (b)
print ('b 拥有相同 id()：')
print (id(b))
print ('修改 b 的形状：')
b.shape =  3,2  
print (b)
print ('a 的形状也修改了：')
print (a)

我们的数组是：
[0 1 2 3 4 5]
调用 id() 函数：
4570771168
a 赋值给 b：
[0 1 2 3 4 5]
b 拥有相同 id()：
4570771168
修改 b 的形状：
[[0 1]
 [2 3]
 [4 5]]
a 的形状也修改了：
[[0 1]
 [2 3]
 [4 5]]


## 视图或浅拷贝
## ndarray.view() 方会创建一个新的数组对象，该方法创建的新数组的维数更改不会更改原始数据的维数。

In [6]:
a = np.arange(6).reshape(3,2)  
print ('数组 a：')
print (a)
print ('创建 a 的视图：')
b = a.view()  
print (b)
print ('两个数组的 id() 不同：')
print ('a 的 id()：')
print (id(a))
print ('b 的 id()：' )
print (id(b))
# 修改 b 的形状，并不会修改 a
b.shape =  2,3
print ('b 的形状：')
print (b)
print ('a 的形状：')
print (a)

数组 a：
[[0 1]
 [2 3]
 [4 5]]
创建 a 的视图：
[[0 1]
 [2 3]
 [4 5]]
两个数组的 id() 不同：
a 的 id()：
4570837120
b 的 id()：
4570837280
b 的形状：
[[0 1 2]
 [3 4 5]]
a 的形状：
[[0 1]
 [2 3]
 [4 5]]


## 使用切片创建视图修改数据会影响到原始数组
变量 a,b 都是 arr 的一部分视图，对视图的修改会直接反映到原数据中。但是我们观察 a,b 的 id，他们是不同的，也就是说，视图虽然指向原数据，但是他们和赋值引用还是有区别的。

In [7]:
arr = np.arange(12)
print ('我们的数组：')
print (arr)
print ('创建切片：')
a=arr[3:]
b=arr[3:]
a[1]=123
b[2]=234
print(arr)
print(id(a),id(b),id(arr[3:]))

我们的数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11]
创建切片：
[  0   1   2   3 123 234   6   7   8   9  10  11]
4570837760 4570837120 4570771008


## 副本或深拷贝
ndarray.copy() 函数创建一个副本。 对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置。

In [8]:
a = np.array([[10,10],  [2,3],  [4,5]])  
print ('数组 a：')
print (a)
print ('创建 a 的深层副本：')
b = a.copy()  
print ('数组 b：')
print (b)
# b 与 a 不共享任何内容  
print ('我们能够写入 b 来写入 a 吗？')
print (b is a)
print ('修改 b 的内容：')
b[0,0]  =  100  
print ('修改后的数组 b：')
print (b)
print ('a 保持不变：')
print (a)

数组 a：
[[10 10]
 [ 2  3]
 [ 4  5]]
创建 a 的深层副本：
数组 b：
[[10 10]
 [ 2  3]
 [ 4  5]]
我们能够写入 b 来写入 a 吗？
False
修改 b 的内容：
修改后的数组 b：
[[100  10]
 [  2   3]
 [  4   5]]
a 保持不变：
[[10 10]
 [ 2  3]
 [ 4  5]]


# NumPy 矩阵(Matrix)和线性代数

In [4]:
import numpy as np
import numpy.matlib 

## matlib.empty()
matlib.empty() 函数返回一个新的矩阵，语法格式为：

numpy.matlib.empty(shape, dtype, order)

参数说明：  
shape: 定义新矩阵形状的整数或整数元组  
Dtype: 可选，数据类型  
order: C（行序优先） 或者 F（列序优先）  

## numpy.matlib.zeros()
numpy.matlib.zeros() 函数创建一个以 0 填充的矩阵。

## numpy.matlib.ones()
numpy.matlib.ones()函数创建一个以 1 填充的矩阵。

## numpy.matlib.eye()
numpy.matlib.eye() 函数返回一个矩阵，对角线元素为 1，其他位置为零。

numpy.matlib.eye(n, M,k, dtype)

参数说明：
n: 返回矩阵的行数  
M: 返回矩阵的列数，默认为 n  
k: 对角线的索引  
dtype: 数据类型  

In [15]:
a = np.matlib.eye(3)
print(a)
printline()
b = np.matlib.eye(n =  3, M =  4, k =  0, dtype =  float)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## numpy.matlib.identity()
numpy.matlib.identity() 函数返回给定大小的单位矩阵。

单位矩阵是个方阵，从左上角到右下角的对角线（称为主对角线）上的元素均为 1，除此以外全都为 0。

In [16]:
print (np.matlib.identity(5, dtype =  float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## numpy.matlib.rand()
numpy.matlib.rand() 函数创建一个给定大小的矩阵，数据是随机填充的。

In [18]:
print(np.matlib.rand(4,4))

[[0.4282776  0.50915809 0.74955127 0.4625604 ]
 [0.70243822 0.43180625 0.09140991 0.7412289 ]
 [0.07368735 0.98197835 0.56568478 0.76572963]
 [0.34971753 0.02204905 0.51309213 0.50028528]]


## numpy.matrix()

In [21]:
i = np.matrix('1,2;3,4')  
print (i)
print(type(i))

[[1 2]
 [3 4]]
<class 'numpy.matrixlib.defmatrix.matrix'>


## 转换成array方法  numpy.asarray()

In [24]:
j = np.asarray(i)  
print (j)
print(type(j))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


## 转换成matrix方法  numpy.asmatrix()

In [26]:
k = np.asmatrix(j)  
print (k)
print(type(k))

[[1 2]
 [3 4]]
<class 'numpy.matrixlib.defmatrix.matrix'>


## 函数库 linalg
dot	两个数组的点积  
vdot	两个向量的点积  
inner	两个数组的内积  
matmul	两个数组的矩阵积  
determinant	数组的行列式  
solve	求解线性矩阵方程  
inv	计算矩阵的乘法逆矩阵  

### numpy.dot(a, b, out=None) 
dot	两个数组的点积 二维数组相当于 矩阵乘积  
a : ndarray 数组  
b : ndarray 数组  
out : ndarray, 可选，用来保存dot()的计算结果  

In [49]:
a = np.array([[1,2],[1,3]])
b = np.array([[3,5],[5,5]])
print(np.dot(a,b))

[[13 15]
 [18 20]]


### numpy.vdot()
numpy.vdot() 函数是两个向量的点积(对应位置乘积全部相加)。 如果第一个参数是复数，那么它的共轭复数会用于计算。 如果参数是多维数组，它会被展开。

In [28]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积
print (np.vdot(a,b))

130


$1*11 + 2*12 + 3*13 + 4*14 = 130$

### numpy.inner()
numpy.inner() 函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。

In [29]:
print (np.inner(np.array([1,2,3]),np.array([0,1,0])))

2


$1*0+2*1+3*0=2$

In [30]:
a = np.array([[1,2], [3,4]]) 
 
print ('数组 a：')
print (a)
b = np.array([[11, 12], [13, 14]]) 
 
print ('数组 b：')
print (b)
 
print ('内积：')
print (np.inner(a,b))

数组 a：
[[1 2]
 [3 4]]
数组 b：
[[11 12]
 [13 14]]
内积：
[[35 41]
 [81 95]]


第一行第一行$1*11+2*12,   第一行第二行1*13+2*14 $  
第二行第一行$3*11+4*12,   第二行第二行3*13+4*14 $

### numpy.matmul
numpy.matmul 函数返回两个数组的矩阵乘积。 虽然它返回二维数组的正常乘积，但如果任一参数的维数大于2，则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。

另一方面，如果任一参数是一维数组，则通过在其维度上附加 1 来将其提升为矩阵，并在乘法之后被去除。

对于二维数组，它就是矩阵乘法：

In [31]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [32]:
a = [[1,0],[0,1]] 
b = [1,2] 
print (np.matmul(a,b))
print (np.matmul(b,a))

[1 2]
[1 2]


In [33]:
a = np.arange(8).reshape(2,2,2) 
b = np.arange(4).reshape(2,2) 
print (np.matmul(a,b))

[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


### numpy.linalg.det()
numpy.linalg.det() 函数计算输入矩阵的行列式。

行列式在线性代数中是非常有用的值。 它从方阵的对角元素计算。 对于 2×2 矩阵，它是左上和右下元素的乘积与其他两个的乘积的差。

换句话说，对于矩阵[[a，b]，[c，d]]，行列式计算为 ad-bc。 较大的方阵被认为是 2×2 矩阵的组合。

In [34]:
a = np.array([[1,2], [3,4]]) 
 
print (np.linalg.det(a))

-2.0000000000000004


In [36]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print (b)
print (np.linalg.det(b))
print (6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


### numpy.linalg.solve()
numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解。

In [52]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
b = np.array([[6],[-4],[27]]) 
c = np.linalg.solve(a,b)
print(c)

[[ 5.]
 [ 3.]
 [-2.]]


或者 求 $ A^{-1}$ 与 B 的矩阵乘积
方法一：转换成矩阵，用 I求逆矩阵

In [53]:
d = np.asmatrix(a).I
c = np.matmul(d,b)
print(c)

[[ 5.]
 [ 3.]
 [-2.]]


方法二：用 numpy.linalg.inv()求逆矩阵

In [54]:
d = np.linalg.inv(a)
c = np.dot(d,b)
print(c)

[[ 5.]
 [ 3.]
 [-2.]]


### numpy.linalg.inv()
numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵。

逆矩阵（inverse matrix）：设A是数域上的一个n阶矩阵，若在相同数域上存在另一个n阶矩阵B，使得： AB=BA=E ，则我们称B是A的逆矩阵，而A则被称为可逆矩阵。注：E为单位矩阵。

In [47]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x)
print (y)
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
